import test from 'node:test';
import assert from 'node:assert/strict';
import {publishFinance} from '../scripts/publish-finance.mjs';
import {createInstituteService,createMemoryInstituteStore,validateFinance} from '../cloudflare-worker/src/institute.mjs';
const fixture=(version='v1')=>({schemaVersion:1,source:{version,file:'synthetic.xlsx',asOf:'2026-09-01'},opening:{availableCents:100,lockedCents:0,asOf:'2026-09-01'},months:[{month:'2026-09',incomeCents:20,expenseCents:0,balanceCents:120}],items:[{id:'test',month:'2026-09',name:'合成数据',direction:'income',amountCents:20}],rules:[]});
async function setup(){const store=createMemoryInstituteStore();await store.putFinance(0,validateFinance(fixture()),new Date().toISOString());const service=createInstituteService({store,checkPassword:async p=>p==='000000',allowedOrigin:'https://kaneshiroakatsuki.github.io'});const calls=[];return {store,calls,fetchImpl:async(url,init)=>{calls.push({path:new URL(url).pathname,method:init.method});return service.handle(new Request(url,init));}};}
test('budget check is read-only and revokes its temporary login',async()=>{const s=await setup();const r=await publishFinance({...s,document:fixture('v2'),password:'000000'});assert.equal(r.status,'checked');assert.equal(r.revision,1);assert.equal(r.temporaryLoginRevoked,true);assert(!s.calls.some(c=>c.method==='PUT'));assert.equal((await s.store.list(new Date().toISOString())).length,0);});
test('identical publication does not bump revision',async()=>{const s=await setup();const r=await publishFinance({...s,document:fixture(),password:'000000',mode:'publish',expectedRevision:1});assert.equal(r.status,'already-current');assert.equal((await s.store.getFinance()).revision,1);});
test('publication reads back the exact document and clears login',async()=>{const s=await setup();const r=await publishFinance({...s,document:fixture('v2'),password:'000000',mode:'publish',expectedRevision:1});assert.equal(r.status,'published-and-verified');assert.equal(r.revision,2);assert.deepEqual((await s.store.getFinance()).document,validateFinance(fixture('v2')));assert.equal((await s.store.list(new Date().toISOString())).length,0);});
test('stale revision and older snapshot are blocked without writes',async()=>{for(const [version,revision]of [['v2',0],['v0',1]]){const s=await setup();await assert.rejects(publishFinance({...s,document:fixture(version),password:'000000',mode:'publish',expectedRevision:revision}));assert.equal((await s.store.getFinance()).revision,1);assert.equal((await s.store.list(new Date().toISOString())).length,0);}});
test('invalid totals fail before credentials leave the process',async()=>{const s=await setup(),d=fixture();d.months[0].incomeCents=21;await assert.rejects(publishFinance({...s,document:d,password:'000000'}));assert.equal(s.calls.length,0);});
test('publish requires explicit expected revision',async()=>{const s=await setup();await assert.rejects(publishFinance({...s,document:fixture('v2'),password:'000000',mode:'publish'}));assert.equal(s.calls.length,0);});
test('failed revocation is reported and never falsely marked complete',async()=>{const s=await setup(),original=s.fetchImpl;const r=await publishFinance({...s,document:fixture(),password:'000000',fetchImpl:(url,init)=>url.endsWith('/api/sessions')?Promise.reject(new Error('synthetic network failure')):original(url,init)});assert.equal(r.temporaryLoginRevoked,false);});
test('concurrent update between GET and PUT cannot be overwritten',async()=>{const s=await setup(),original=s.fetchImpl;await assert.rejects(publishFinance({...s,document:fixture('v2'),password:'000000',mode:'publish',expectedRevision:1,fetchImpl:async(url,init)=>{if(url.endsWith('/api/finance')&&init.method==='PUT')await s.store.putFinance(1,validateFinance(fixture('v3')),new Date().toISOString());return original(url,init);}}),/版本已变化/);assert.equal((await s.store.getFinance()).document.source.version,'v3');assert.equal((await s.store.list(new Date().toISOString())).length,0);});
test('uncertain readback fails without pretending that upload did not occur',async()=>{const s=await setup(),original=s.fetchImpl;let uploaded=false;await assert.rejects(publishFinance({...s,document:fixture('v2'),password:'000000',mode:'publish',expectedRevision:1,fetchImpl:async(url,init)=>{if(uploaded&&url.endsWith('/api/finance')&&init.method==='GET')throw new Error('Readback unavailable; verify before retry');const r=await original(url,init);if(init.method==='PUT')uploaded=true;return r;}}),/verify before retry/);assert.equal((await s.store.getFinance()).revision,2);assert.equal((await s.store.list(new Date().toISOString())).length,0);});
